### ISSUE TITLE
No Chargeback calculation available for support

### ISSUE THREAD

**Issue by davinder26** [waliaabhishek/chitragupta#11]
Hello @waliaabhishek 
getting this messge
No Chargeback calculation available for support

Prometheus is running  with below metrics-
confluent_cloud_api_key

confluent_cloud_billing_details

confluent_cloud_chargeback_details

confluent_cloud_custom_scrape_status

confluent_cloud_kafka_cluster

confluent_cloud_user

but data is not displaying in grafana

**Comment by waliaabhishek** [comment]
> No Chargeback calculation available for support

I think this is a miss on my part. I will try to add this to the codebase soon. For now, everything else will work, but the support cost will not be divided up between different entities.

> but data is not displaying in grafana

For this one, The chargeback calculator start about 200 days in the past to calculate. What I have seen is that it takes about a minute per data to fetch, cleanse, calculate, and shipping it to prometheus. There are 2 sugggestions that I can give:

- Start the compose and let it run through (considering you checked the logs and there are no errors)
- Shorten the rewind time [here](https://github.com/waliaabhishek/ccloud-chargeback-helper/blob/145fac91b79e953965ae81c7c60029d886335228/.env#L5) to a much lower value (like 30) to not fetch all the historical dataset.

**Comment by davinder26** [comment]
@waliaabhishek  Thanks , Its working now.

**Comment by waliaabhishek** [comment]
Thank you for the confirmation.
