### ISSUE TITLE
Unable to  visualize historical data

### ISSUE THREAD

**Issue by davinder26** [waliaabhishek/chitragupta#12]
@waliaabhishek  I can see data only for current month.Can I see last six months data

**Comment by waliaabhishek** [comment]
You will need to change [this](https://github.com/waliaabhishek/ccloud-chargeback-helper/blob/145fac91b79e953965ae81c7c60029d886335228/.env#L5) value to more than 180 and restart the code in order to start filling in the older data.

**Comment by davinder26** [comment]
@waliaabhishek  Thanks! 
@waliaabhishek  common_charge_ratio = 0.30
usage_charge_ratio = 0.70
above values different for  every users ,we can change or not.

**Comment by waliaabhishek** [comment]
This control is not exposed outside of the main program and is a constant in the codebase. It cannot be changed.

**Comment by davinder26** [comment]
@waliaabhishek  Billing price is not matched with actual billing price.
