### ISSUE TITLE
Confluent prices does not match with grafana

### ISSUE THREAD

**Issue by davinder26** [waliaabhishek/chitragupta#13]
@waliaabhishek  @pneff93  Confluent prices does not match with grafana  ,Do I need to modify anything in code

**Comment by waliaabhishek** [comment]
The code for checked for accuracies for billing data and should not have any discrepancy. Can you check the logs and see if there are any issues that the code is sending to the logs ?

**Comment by davinder26** [comment]
@waliaabhishek   env file parameters.

CCLOUD_BILLING_API_KEY=***************
CCLOUD_BILLING_API_SECRET=**************************
CHARGEBACK_SERVER_URL=http://prometheus_for_chargeback:9090
CHARGEBACK_METRICS_URL=http://ccloud_chargeback_handler:8000
CHARGEBACK_READINESS_PROBE_URL=http://ccloud_chargeback_handler:8001
METRICS_API_SERVER_URL=http://prometheus_for_chargeback:9090
METRICS_API_SERVER_ENABLE_AUTH=False
METRICS_API_SERVER_AUTH_TYPE=HTTPBasicAuth
LOG_LEVEL="DEBUG"
ENABLE_METHOD_BREADCRUMBS=True

**Comment by davinder26** [comment]
@waliaabhishek  Any suggestions

**Comment by davinder26** [comment]
@waliaabhishek  I also used https://github.com/confluentinc/jmx-monitoring-stacks/tree/main/ccloud-prometheus-grafana repo.With this repo data is matching.But displaying only for current month.
Anthing wrong in env file parameters.

**Comment by davinder26** [comment]
@waliaabhishek  its working fine
